

export const shopTypes = {
  GET_DENIM: "GET_DENIM",
  GET_SHIRTS: "GET_SHIRTS",
  GET_SHORTS: "GET_SHORTS",
  GET_DRESSES: "GET_DRESSES",
  GET_JACKETS: "GET_JACKETS",
  GET_JEANS: "GET_JEANS",
  GET_TOPS: "GET_TOPS",
};